name: main
on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: get the count of requested reviewers
        run: |
          length=$(echo $requested_reviewers)
          echo "length = $length"
        env:
          requested_reviewers: ${{ toJson(github.event.pull_request.requested_reviewers) }}

