name: Test 65 # Related to https://stackoverflow.com/questions/18995854/how-can-i-use-github-api-to-get-all-tags-or-releases-for-a-project

on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --http3 https://api.github.com/repos/jarhead-killgrave/EasyTask/tags
        env:
          TOKEN: ${{ secrets.ACCESS_TOKEN }}
