name: Vérifier les validations de pull request

on:
  pull_request:

jobs:
  verify_pr_approvals:
    runs-on: ubuntu-latest

    steps:
      - run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --http2 https://api.github.com/repos/jarhead-killgrave/EasyTask/tags
        env:
          TOKEN: ${{ secrets.ACCESS_TOKEN }}
